author: eccentric_nz
description: Allows you to store your XP by clicking on a special sign
main: me.eccentric_nz.xpkeeper.XPKeeper
dev-url: http://dev.bukkit.org/bukkit-plugins/xpkeeper/
name: XPKeeper
load: POSTWORLD
version: 1.8
api-version: 1.17
permissions:
  xpkeeper.use:
    description: Allow players to use XPKeeper signs
    default: true
  xpkeeper.fist:
    description: Allow players to toggle must_use_fist true|false
    default: op
  xpkeeper.limit:
    description: Allow players to toggle set_limits true|false
    default: op
  xpkeeper.limit.bypass:
    description: Allow players to bypass limits
    default: op
  xpkeeper.force:
    description: Allow players to force remove player data
    default: op
  xpkeeper.admin:
    description: Allow players to set/give XP
    default: op
  xpkeeper.editsign:
    description: Allow players to edit signs
    default: op
commands:
  xpkgive:
    aliases: [ xpkg ]
    description: Give a player some XP.
    usage: /<command> [player] [amount]
    permission: xpkeeper.admin
    permission-message: You don't have the permission <permission> to use this command
  xpkset:
    aliases: [ xpks ]
    description: Set a player's total XP.
    usage: /<command> [player] [amount]
    permission: xpkeeper.admin
    permission-message: You don't have the permission <permission> to use this command
  xpkremove:
    aliases: [ xpkr, xpkrem ]
    description: Remove an XPKeeper sign.
    usage: /<command>
    permission: xpkeeper.use
    permission-message: You don't have the permission <permission> to use this command
  xpkupdate:
    aliases: [ xpku ]
    description: Update an XPKeeper sign to add persistent UUID data.
    usage: /<command>
    permission: xpkeeper.use
    permission-message: You don't have the permission <permission> to use this command
  xpkforceremove:
    aliases: [ xpkfr, xpkforce ]
    description: Remove ALL player data from the database - use with caution.
    usage: /<command> [player]
  xpkfist:
    aliases: [ xpkf ]
    description: Toggle the XPKeeper must_use_fist config option.
    usage: /<command>
    permission: xpkeeper.fist
    permission-message: You don't have the permission <permission> to use this command
  xpkedit:
    aliases: [ xpke ]
    description: Edit the first line of the XPKeeper sign.
    usage: /<command>
    permission: xpkeeper.editsign
    permission-message: You don't have the permission <permission> to use this command
  xpkpay:
    aliases: [ xpkp ]
    description: Pay another player some XP.
    usage: /<command> [player] [amount]
    permission: xpkeeper.use
    permission-message: You don't have the permission <permission> to use this command
  xpkwithdraw:
    aliases: [ xpkw, xpkwd ]
    description: Set the amount, in levels, that is withdrawn from an XPKeeper sign. 0 = all.
    usage: /<command> [amount]
    permission: xpkeeper.admin
    permission-message: You don't have the permission <permission> to use this command
  xpklimit:
    aliases: [ xpkl ]
    description: Toggle the XPKeeper set_limits config option.
    usage: /<command>
    permission: xpkeeper.limit
    permission-message: You don't have the permission <permission> to use this command
  xpkreload:
    aliases: [ xpkrl ]
    description: Reloads the config file.
    usage: /<command>
    permission: xpkeeper.admin
    permission-message: You don't have the permission <permission> to use this command
  xpkcolour:
    aliases: [ xpkc,xpkcolor ]
    description: Sets 'firstline_colour' in the config file.
    usage: /<command> [colour code e.g. &6]
    permission: xpkeeper.admin
    permission-message: You don't have the permission <permission> to use this command
