author: eccentric_nz
description: Allows you to store your XP by clicking on a special sign
main: me.eccentric_nz.xpkeeper.XPKeeper
dev-url: https://github.com/eccentricdevotion/XPKeeper
name: XPKeeper
load: POSTWORLD
version: 2.0.0
api-version: 26.2
permissions:
  xpkeeper.use:
    description: Allow players to use XPKeeper signs
    default: true
  xpkeeper.pay:
    description: Allow players to pay other players XP
    default: true
  xpkeeper.fist:
    description: Allow players to toggle must_use_fist true|false
    default: op
  xpkeeper.limit:
    description: Allow players to toggle set_limits true|false
    default: op
  xpkeeper.limit.bypass:
    description: Allow players to bypass limits
    default: op
  xpkeeper.force:
    description: Allow players to force remove player data
    default: op
  xpkeeper.admin:
    description: Allow players to set/give XP
    default: op
  xpkeeper.editsign:
    description: Allow players to edit signs
    default: op
